name: Evaldo Junior (InFog)
description: A blog about GNU/Linux, PHP, Python and other development tools, IT and general geek stuff.
url: http://blog.evaldojunior.com
markdown: kramdown
highlighter: rouge
timezone: Europe/Berlin
paginate: 10
gems: [jekyll-paginate]
defaults:
  -
    scope:
      path: ""
      type: posts
    values:
      mainimage: "default.jpg"
  -
    scope:
      path: ""
      type: posts
    values:
      mainimage: "default.jpg"
