name: Evaldo Junior (InFog)
description: A blog about GNU/Linux, PHP, Python and other development, IT and general geek stuff.
url: http://blog.evaldojunior.com
markdown: redcarpet
highlighter: true
timezone: Europe/Berlin
paginate: 10
